// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: landing.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - hello.LandingService

/// Namespace containing generated types for the "hello.LandingService" service.
public enum Hello_LandingService {
    /// Service descriptor for the "hello.LandingService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "Talk" metadata.
        public enum Talk {
            /// Request type for "Talk".
            public typealias Input = Hello_TalkRequest
            /// Response type for "Talk".
            public typealias Output = Hello_TalkResponse
            /// Descriptor for "Talk".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService"),
                method: "Talk"
            )
        }
        /// Namespace for "TalkOneAnswerMore" metadata.
        public enum TalkOneAnswerMore {
            /// Request type for "TalkOneAnswerMore".
            public typealias Input = Hello_TalkRequest
            /// Response type for "TalkOneAnswerMore".
            public typealias Output = Hello_TalkResponse
            /// Descriptor for "TalkOneAnswerMore".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService"),
                method: "TalkOneAnswerMore"
            )
        }
        /// Namespace for "TalkMoreAnswerOne" metadata.
        public enum TalkMoreAnswerOne {
            /// Request type for "TalkMoreAnswerOne".
            public typealias Input = Hello_TalkRequest
            /// Response type for "TalkMoreAnswerOne".
            public typealias Output = Hello_TalkResponse
            /// Descriptor for "TalkMoreAnswerOne".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService"),
                method: "TalkMoreAnswerOne"
            )
        }
        /// Namespace for "TalkBidirectional" metadata.
        public enum TalkBidirectional {
            /// Request type for "TalkBidirectional".
            public typealias Input = Hello_TalkRequest
            /// Response type for "TalkBidirectional".
            public typealias Output = Hello_TalkResponse
            /// Descriptor for "TalkBidirectional".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService"),
                method: "TalkBidirectional"
            )
        }
        /// Descriptors for all methods in the "hello.LandingService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Talk.descriptor,
            TalkOneAnswerMore.descriptor,
            TalkMoreAnswerOne.descriptor,
            TalkBidirectional.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "hello.LandingService" service.
    public static let hello_LandingService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "hello.LandingService")
}

// MARK: hello.LandingService (server)

extension Hello_LandingService {
    /// Streaming variant of the service protocol for the "hello.LandingService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "Talk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > nary RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talk(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>

        /// Handle the "TalkOneAnswerMore" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > erver streaming RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talkOneAnswerMore(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>

        /// Handle the "TalkMoreAnswerOne" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > lient streaming RPC with random & sleep
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talkMoreAnswerOne(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>

        /// Handle the "TalkBidirectional" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > idirectional streaming RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talkBidirectional(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>
    }

    /// Service protocol for the "hello.LandingService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Hello_LandingService.StreamingServiceProtocol {
        /// Handle the "Talk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > nary RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Hello_TalkResponse` message.
        func talk(
            request: GRPCCore.ServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Hello_TalkResponse>

        /// Handle the "TalkOneAnswerMore" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > erver streaming RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talkOneAnswerMore(
            request: GRPCCore.ServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>

        /// Handle the "TalkMoreAnswerOne" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > lient streaming RPC with random & sleep
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Hello_TalkResponse` message.
        func talkMoreAnswerOne(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Hello_TalkResponse>

        /// Handle the "TalkBidirectional" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > idirectional streaming RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Hello_TalkResponse` messages.
        func talkBidirectional(
            request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse>
    }

    /// Simple service protocol for the "hello.LandingService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Hello_LandingService.ServiceProtocol {
        /// Handle the "Talk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > nary RPC
        ///
        /// - Parameters:
        ///   - request: A `Hello_TalkRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Hello_TalkResponse` to respond with.
        func talk(
            request: Hello_TalkRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Hello_TalkResponse

        /// Handle the "TalkOneAnswerMore" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > erver streaming RPC
        ///
        /// - Parameters:
        ///   - request: A `Hello_TalkRequest` message.
        ///   - response: A response stream of `Hello_TalkResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func talkOneAnswerMore(
            request: Hello_TalkRequest,
            response: GRPCCore.RPCWriter<Hello_TalkResponse>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "TalkMoreAnswerOne" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > lient streaming RPC with random & sleep
        ///
        /// - Parameters:
        ///   - request: A stream of `Hello_TalkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Hello_TalkResponse` to respond with.
        func talkMoreAnswerOne(
            request: GRPCCore.RPCAsyncSequence<Hello_TalkRequest, any Swift.Error>,
            context: GRPCCore.ServerContext
        ) async throws -> Hello_TalkResponse

        /// Handle the "TalkBidirectional" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > idirectional streaming RPC
        ///
        /// - Parameters:
        ///   - request: A stream of `Hello_TalkRequest` messages.
        ///   - response: A response stream of `Hello_TalkResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func talkBidirectional(
            request: GRPCCore.RPCAsyncSequence<Hello_TalkRequest, any Swift.Error>,
            response: GRPCCore.RPCWriter<Hello_TalkResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Hello_LandingService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Hello_LandingService.Method.Talk.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkResponse>(),
            handler: { request, context in
                try await self.talk(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Hello_LandingService.Method.TalkOneAnswerMore.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkResponse>(),
            handler: { request, context in
                try await self.talkOneAnswerMore(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Hello_LandingService.Method.TalkMoreAnswerOne.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkResponse>(),
            handler: { request, context in
                try await self.talkMoreAnswerOne(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Hello_LandingService.Method.TalkBidirectional.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkResponse>(),
            handler: { request, context in
                try await self.talkBidirectional(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Hello_LandingService.ServiceProtocol {
    public func talk(
        request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse> {
        let response = try await self.talk(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func talkOneAnswerMore(
        request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse> {
        let response = try await self.talkOneAnswerMore(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }

    public func talkMoreAnswerOne(
        request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse> {
        let response = try await self.talkMoreAnswerOne(
            request: request,
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Hello_LandingService.SimpleServiceProtocol {
    public func talk(
        request: GRPCCore.ServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Hello_TalkResponse> {
        return GRPCCore.ServerResponse<Hello_TalkResponse>(
            message: try await self.talk(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func talkOneAnswerMore(
        request: GRPCCore.ServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse> {
        return GRPCCore.StreamingServerResponse<Hello_TalkResponse>(
            metadata: [:],
            producer: { writer in
                try await self.talkOneAnswerMore(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func talkMoreAnswerOne(
        request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Hello_TalkResponse> {
        return GRPCCore.ServerResponse<Hello_TalkResponse>(
            message: try await self.talkMoreAnswerOne(
                request: request.messages,
                context: context
            ),
            metadata: [:]
        )
    }

    public func talkBidirectional(
        request: GRPCCore.StreamingServerRequest<Hello_TalkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Hello_TalkResponse> {
        return GRPCCore.StreamingServerResponse<Hello_TalkResponse>(
            metadata: [:],
            producer: { writer in
                try await self.talkBidirectional(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: hello.LandingService (client)

extension Hello_LandingService {
    /// Generated client protocol for the "hello.LandingService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Talk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > nary RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func talk<Result>(
            request: GRPCCore.ClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TalkOneAnswerMore" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > erver streaming RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func talkOneAnswerMore<Result>(
            request: GRPCCore.ClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TalkMoreAnswerOne" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > lient streaming RPC with random & sleep
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Hello_TalkRequest` messages.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func talkMoreAnswerOne<Result>(
            request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "TalkBidirectional" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > idirectional streaming RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Hello_TalkRequest` messages.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func talkBidirectional<Result>(
            request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "hello.LandingService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Talk" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > nary RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func talk<Result>(
            request: GRPCCore.ClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Hello_LandingService.Method.Talk.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TalkOneAnswerMore" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > erver streaming RPC
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Hello_TalkRequest` message.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func talkOneAnswerMore<Result>(
            request: GRPCCore.ClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Hello_LandingService.Method.TalkOneAnswerMore.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TalkMoreAnswerOne" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > lient streaming RPC with random & sleep
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Hello_TalkRequest` messages.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func talkMoreAnswerOne<Result>(
            request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.clientStreaming(
                request: request,
                descriptor: Hello_LandingService.Method.TalkMoreAnswerOne.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "TalkBidirectional" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > idirectional streaming RPC
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Hello_TalkRequest` messages.
        ///   - serializer: A serializer for `Hello_TalkRequest` messages.
        ///   - deserializer: A deserializer for `Hello_TalkResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func talkBidirectional<Result>(
            request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
            serializer: some GRPCCore.MessageSerializer<Hello_TalkRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Hello_TalkResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: Hello_LandingService.Method.TalkBidirectional.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Hello_LandingService.ClientProtocol {
    /// Call the "Talk" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > nary RPC
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Hello_TalkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talk<Result>(
        request: GRPCCore.ClientRequest<Hello_TalkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.talk(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkOneAnswerMore" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > erver streaming RPC
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Hello_TalkRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkOneAnswerMore<Result>(
        request: GRPCCore.ClientRequest<Hello_TalkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.talkOneAnswerMore(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkMoreAnswerOne" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > lient streaming RPC with random & sleep
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Hello_TalkRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkMoreAnswerOne<Result>(
        request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.talkMoreAnswerOne(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkBidirectional" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > idirectional streaming RPC
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Hello_TalkRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkBidirectional<Result>(
        request: GRPCCore.StreamingClientRequest<Hello_TalkRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.talkBidirectional(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Hello_TalkRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Hello_TalkResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Hello_LandingService.ClientProtocol {
    /// Call the "Talk" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > nary RPC
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talk<Result>(
        _ message: Hello_TalkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Hello_TalkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.talk(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkOneAnswerMore" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > erver streaming RPC
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkOneAnswerMore<Result>(
        _ message: Hello_TalkRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Hello_TalkRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.talkOneAnswerMore(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkMoreAnswerOne" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > lient streaming RPC with random & sleep
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkMoreAnswerOne<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Hello_TalkRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Hello_TalkResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Hello_TalkRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.talkMoreAnswerOne(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "TalkBidirectional" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > idirectional streaming RPC
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func talkBidirectional<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Hello_TalkRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Hello_TalkResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Hello_TalkRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.talkBidirectional(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}