#!/bin/bash

# Kotlin TLS 验证脚本
# 使用两个终端窗口的方式

echo "=========================================="
echo "Kotlin TLS 验证指南"
echo "=========================================="
echo ""
echo "请按照以下步骤在两个终端中操作："
echo ""
echo "终端 1 - 启动服务器："
echo "  cd hello-grpc-kotlin"
echo "  bash scripts/server_start.sh --tls --port=9996"
echo ""
echo "终端 2 - 运行客户端："
echo "  cd hello-grpc-kotlin"
echo "  bash scripts/client_start.sh --tls --addr=localhost:9996"
echo ""
echo "=========================================="
echo "或者测试非 TLS 模式："
echo "=========================================="
echo ""
echo "终端 1 - 启动服务器："
echo "  cd hello-grpc-kotlin"
echo "  bash scripts/server_start.sh --port=9996"
echo ""
echo "终端 2 - 运行客户端："
echo "  cd hello-grpc-kotlin"
echo "  bash scripts/client_start.sh --addr=localhost:9996"
echo ""
echo "=========================================="
echo "当前状态总结"
echo "=========================================="
echo ""
echo "✅ 脚本已标准化"
echo "  - scripts/server_start.sh"
echo "  - scripts/client_start.sh"
echo "  - 支持 --tls 参数"
echo "  - 证书路径自动检测"
echo ""
echo "✅ 非 TLS 模式"
echo "  - 服务器可以启动"
echo "  - 客户端可以连接"
echo "  - 基本通信正常"
echo ""
echo "⚠️  TLS 模式"
echo "  - 服务器可以启动"
echo "  - 证书加载成功"
echo "  - 客户端 TLS 握手失败"
echo ""
echo "问题："
echo "  客户端报错: UNAVAILABLE: io exception"
echo "  Channel Pipeline: [SslHandler#0, ProtocolNegotiators\$ClientTlsHandler#0, ...]"
echo ""
echo "可能原因："
echo "  1. 证书链验证问题"
echo "  2. 服务器名称验证（SNI）"
echo "  3. SSL/TLS 协议版本"
echo ""
echo "详细信息请查看: TLS_STATUS.md"
echo ""
