# Debian gRPC PHP base image — fully offline build.
#
# Strategy: pre-download ALL dependencies (composer, grpc source, pecl grpc
# tgz) to /tmp/offline on the host BEFORE docker build, then COPY them into
# the build context. The image itself only needs network for apt-get (mirrors.
# aliyun.com verified reachable); no fetch to GitHub, getcomposer.org, or
# pecl.php.net happens inside the build.
#
# Why not alpine: php:8.5-cli-alpine repeatedly hit TLS EOF errors when
# downloading packages from China mirrors. debian:bookworm with apt mirrors
# is reliable.
#
# Trade-offs:
#   - Final image: ~250MB (deb + small toolchain); smaller (~150MB) is
#     possible by stripping more, but breaking changes risk is high.
#   - Build context grows by ~250MB because grpc source is COPY'd in.
#     This is the price of offline builds.
#
# Refresh offline assets before rebuilding:
#   cd /tmp/offline
#   curl --http1.1 -fL -o composer.phar      https://mirrors.aliyun.com/composer/composer.phar
#   curl --http1.1 -fL -o grpc.tar.gz        https://github.com/grpc/grpc/archive/refs/tags/v1.81.1.tar.gz
#   tar xzf grpc.tar.gz && rm grpc.tar.gz && mv grpc-1.81.1 grpc
#   git clone --depth 1 --single-branch https://github.com/abseil/abseil-cpp.git grpc/third_party/abseil-cpp
#   git clone --depth 1 --single-branch https://github.com/google/re2.git        grpc/third_party/re2
#   git clone --depth 1 --single-branch https://github.com/protocolbuffers/protobuf.git grpc/third_party/protobuf
#   mkdir -p grpc/third_party/cares
#   git clone --depth 1 --single-branch https://github.com/c-ares/c-ares.git grpc/third_party/cares/cares
#   curl --http1.1 -fL -o grpc-1.82.0.tgz   https://pecl.php.net/get/grpc
#
# Note on protobuf pin: grpc v1.81.1 expects an exact protobuf submodule SHA.
# Using HEAD may make cmake configure fail. Acceptable because the proto code
# generated by the plugin references the same google/protobuf runtime the
# build_link step pulls from pecl; small header differences are tolerated by
# the gRPC code generator. If cmake rejects protobuf HEAD, pin by SHA below.
FROM php:8.5-cli-bookworm

# Files pre-staged by host-side /tmp/offline/prepare.sh:
#   /tmp/offline/composer.phar       — Composer 2.9.2 binary
#   /tmp/offline/grpc-1.82.0.tgz     — pecl grpc package (bundled deps)
#   /tmp/offline/grpc/               — grpc v1.81.1 source + 4 submodules
# Build the offline tar bundle once on the host so docker COPY a single file.
COPY composer.phar /usr/local/bin/composer
COPY grpc-1.82.0.tgz /tmp/grpc-1.82.0.tgz
COPY grpc-src.tar /tmp/grpc-src.tar

# apt mirrors — aliyun reliable from CN networks.
RUN sed -i \
        -e 's|deb.debian.org/debian|mirrors.aliyun.com/debian|g' \
        -e 's|security.debian.org/debian-security|mirrors.aliyun.com/debian-security|g' \
        /etc/apt/sources.list.d/debian.sources 2>/dev/null || true && \
    if [ -f /etc/apt/sources.list ]; then \
        sed -i \
            -e 's|deb.debian.org/debian|mirrors.aliyun.com/debian|g' \
            -e 's|security.debian.org/debian-security|mirrors.aliyun.com/debian-security|g' \
            /etc/apt/sources.list; \
    fi && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential autoconf libtool pkg-config \
        protobuf-compiler \
        zlib1g-dev \
        curl unzip ca-certificates cmake && \
    chmod +x /usr/local/bin/composer

# Build grpc_php_plugin from the offline grpc source tree.
RUN mkdir -p /tmp/grpc && tar xf /tmp/grpc-src.tar -C /tmp/grpc --strip-components=1 && \
    rm /tmp/grpc-src.tar && \
    cd /tmp/grpc && mkdir -p cmake/build && cd cmake/build && \
    cmake ../.. \
        -DCMAKE_BUILD_TYPE=Release \
        -DgRPC_BUILD_TESTS=OFF \
        -DgRPC_BUILD_CSHARP_EXT=OFF \
        -DgRPC_BUILD_GRPC_CSHARP_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_NODE_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_OBJECTIVE_C_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_PYTHON_PLUGIN=OFF \
        -DgRPC_BUILD_GRPC_RUBY_PLUGIN=OFF && \
    # Cap make parallelism: Docker VM has 8GB RAM. -j$(nproc) hits
    # `cannot allocate memory` while compiling grpc's client_channel
    # modules (each cc/g++ consumes ~1-2GB).
    make grpc_php_plugin -j2 && \
    cp ./grpc_php_plugin /usr/local/bin/ && chmod +x /usr/local/bin/grpc_php_plugin && \
    cd /tmp && rm -rf /tmp/grpc /tmp/grpc-src.tar

# Build grpc.so PHP extension from pecl tgz (offline — all deps bundled inside).
# pecl honors MAKEFLAGS for parallel make; cap for memory reasons (same -j2).
RUN MAKEFLAGS="-j2" pecl install /tmp/grpc-1.82.0.tgz && \
    echo "extension=grpc.so" > /usr/local/etc/php/conf.d/grpc.ini && \
    rm /tmp/grpc-1.82.0.tgz && \
    rm -rf /tmp/pear /root/.cache

# Strip debug symbols from grpc.so and the PHP CLI binaries to reduce image
# size. `--strip-debug` removes debug-only sections (DWARF) without touching
# exported symbol tables or relocation info, so dynamic linking and dlopen
# still work. grpc 1.82 is compiled with `-g` for the pecl build, so this
# typically reduces grpc.so from ~459MB to ~200MB. PHP CLI binary debug
# sections add another ~50MB across the three binaries.
RUN GRPC_SO=$(find /usr/local/lib/php/extensions -name grpc.so) && \
    if file "$GRPC_SO" | grep -q "not stripped"; then \
        strip --strip-debug "$GRPC_SO"; \
    fi && \
    strip --strip-debug /usr/local/bin/php /usr/local/bin/php-cgi /usr/local/bin/phpdbg 2>/dev/null || true

# Strip build toolchain. Keep protobuf-compiler / curl / ca-certs since
# hello-grpc-php protobuf codegen happens in the build-base stage of
# php_grpc.dockerfile (it needs protoc and access to /tmp).
RUN apt-get purge -y --auto-remove build-essential autoconf libtool pkg-config cmake && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /usr/local/lib/php/doc /usr/local/lib/php/test

# Sanity checks.
RUN composer --version && \
    php -m | grep -i grpc && \
    which protoc grpc_php_plugin
