/* this code was generated by automated tool, 
   should not edit by hand */

export interface LandingService {
  Talk(request: TalkRequest): Promise<TalkResponse>;
  TalkOneAnswerMore(request: TalkRequest): AsyncGenerator<TalkResponse>;
  TalkMoreAnswerOne(request: TalkRequest): Promise<TalkResponse>;
  TalkBidirectional(request: TalkRequest): AsyncGenerator<TalkResponse>;
}

export interface TalkRequest {
  data?: string;
  meta?: string;
}

export interface TalkResponse {
  status?: number;
  results??: TalkResult[];
}

export interface TalkResult {
  id?: number;
  type?: ResultType;
  kv?: string;
}
