name: hello_grpc_flutter_202508051543
description: gRPC client

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  #  https://pub.dev/packages/async
  async: ^2.2.0
  # https://pub.dev/packages/grpc
  grpc: ^4.0.0
  # https://pub.dev/packages/protobuf
  protobuf: ^4.0.0
  # https://pub.dev/packages/http
  http: ^1.1.0
  # https://pub.dev/packages/collection
  collection: ^1.17.1
  #
  # https://pub.dev/packages/uuid
  uuid: ^4.3.3
  # https://pub.dev/packages/fixnum
  fixnum: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
