# Scan this file for changes every 30 seconds
refresh_rate: 30 seconds

appenders:
  # Console appender that writes to stdout with Java-like format
  stdout:
    kind: console
    encoder:
      pattern: "{d(%H:%M:%S%.3f)} {m}{n}"

  # Rolling file appender with Java-like format
  requests:
    kind: rolling_file
    path: "log/hello-grpc.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S%.3f)} [{T}] {l} {M} - {m}{n}"
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 19500kb
      roller:
        kind: fixed_window
        pattern: "log/hello-grpc-{}.log.gz"
        count: 5

# Set the default logging level to "info" and attach both appenders to the root
root:
  level: info
  appenders:
    - stdout
    - requests