package(default_visibility = ["//visibility:public"])

filegroup(
    name = "landing.proto",
    srcs = ["landing.proto"],
    visibility = ["//visibility:public"],
)

# This ensures the directory is treated as a proto package
exports_files(["landing.proto"])
