name: hello_grpc_dart
description: Dart gRPC sample client and server.
publish_to: none

environment:
  sdk: '>=3.0.0'

dependencies:
  #  https://pub.dev/packages/async
  async: ^2.2.0
  # https://pub.dev/packages/grpc
  grpc: ^3.2.3
  # https://pub.dev/packages/protobuf
  protobuf: ^3.1.0
  # https://pub.dev/packages/collection
  collection: ^1.18.0
  #
#  # https://pub.dev/packages/logger
#  logger: ^2.0.2
  # https://pub.dev/packages/logging
  logging: ^1.2.0
  #
  # https://pub.dev/packages/uuid
  uuid: ^4.3.3
  # https://pub.dev/packages/test
  test: ^1.24.6
dev_dependencies:
  # https://pub.dev/packages/lints
  lints: ^3.0.0
