{{- range $lang, $cfg := .Values.servers }}
{{- if $cfg.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ $.Values.namespace }}
  name: grpc-server-{{ $lang }}
  labels:
    app: grpc-server-deploy
    version: {{ $cfg.version }}
spec:
  replicas: {{ $.Values.replicas }}
  selector:
    matchLabels:
      app: grpc-server-deploy
      version: {{ $cfg.version }}
  template:
    metadata:
      labels:
        app: grpc-server-deploy
        version: {{ $cfg.version }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccountName }}
      containers:
        - name: grpc-server-deploy
          image: {{ $cfg.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.port }}
              name: grpc-port
          env:
            - name: GRPC_SERVER_PORT
              value: "{{ $.Values.port }}"
{{- end }}
{{- end }}
