apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: grpc-server-svc
  labels:
    app: grpc-server-svc
spec:
  ports:
    - port: {{ .Values.port }}
      name: grpc-port
  selector:
    app: grpc-server-deploy
